package-lock.json
package.json
src/components/Answer.js
src/components/Answers.js
src/components/Button.js
src/components/FeedbackText.js
src/components/Header.js
src/components/Input.js
src/components/PlayerInfo.js
src/components/PlayerRanking.js
src/components/Question.js
src/components/RankingList.js
src/components/Score.js
src/components/Select.js
src/components/Timer.js
src/pages/Feedback.js
src/pages/Game.js
src/pages/Login.js
src/pages/Ranking.js
src/pages/Settings.js
src/redux/actions/index.js
src/redux/reducers/index.js
src/redux/reducers/myReducer.js
src/redux/store/index.js

-[ ] Requisito 1
-[ ] Requisito 2
-[ ] Requisito 3
-[ ] Requisito 4
-[ ] Requisito 5
-[ ] Requisito 6
-[ ] Requisito 7
-[ ] Requisito 8
-[ ] Requisito 9
-[ ] Requisito 10
-[ ] Requisito 11
-[ ] Requisito 12
-[ ] Requisito 13
-[ ] Requisito 14
-[ ] Requisito 15
-[ ] Requisito 16
-[ ] Requisito 17
-[ ] Requisito 18

[Grupo 14] Setup inicial do Projeto Trivia React Redux

---

src/App.js
src/index.js

---
---
- Artefato 1
- Artefato 2
Escreva abaixo suas observações, coloque o seu "*@user*" *na frente da observação*
---

[GRUPO 21] Tarefa Req 12 - Implementar as rotas da aplicação

---

src/actions/index.js
src/pages/Login.js
src/reducers/fetchQuest.js
src/reducers/index.js
src/reducers/login.js

[Requisito 2]

---

src/App.js
src/components/ButtonPlayGame.js
src/components/InputLogin.js
src/pages/Login.js

---
---
- Artefato 1
- Artefato 2
Escreva abaixo suas observações, coloque o seu "*@user*" *na frente da observação*
---
@Matheus Duarte de Freitas - Aqui eu deixo o meu comentário;
@bumbleBee - E aqui eu deixo o meu;
<texto - ps, apagar exemplos>

[GRUPO 21] Fix Tarefa Req 1 - Otimizar Tela de Login

---

src/App.js
src/components/ButtonConfig.jsx
src/pages/Login.jsx
src/pages/Settings.jsx

[ Amaury Queiroz Jr ] [ Requisito 3 ] Crie um botão que leva a pessoa para tela de configuração

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/Configuracoes.js
src/pages/Jogo.js
src/pages/Login.js
src/redux/actions/index.js
src/redux/reducers/game.js
src/redux/reducers/index.js
src/redux/reducers/login.js
src/redux/store/index.js

[Grupo 16]: Arthur Goulart João Vieira Julia Baptista Tatiane Chiarello

---

src/App.js
src/actions/index.js
src/components/Buttons.js
src/pages/Login.js
src/pages/Settings.js
src/reducers/fetchQuestions.js
src/reducers/index.js

Feitos do requisito 1 ao 4 com sucesso

[REQUISITO 3]

---

src/App.js
src/pages/Game.jsx
src/pages/Login.jsx
src/redux/actions/index.js
src/redux/reducers/apiTrivia.js
src/redux/reducers/index.js
src/services/index.js

Time, o último que aprovar faz o merge e deleta a branch remota. Essa aparece logo após o click no merge. Abs.

[ Grupo 17 ] Requisito 2

---

src/App.js
src/pages/Game.js
src/pages/Login.css
src/pages/Login.js
src/pages/Settings.js

requisitos login

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/Login.jsx
src/redux/action/index.js
src/redux/reducer/index.js
src/redux/reducer/userReducer.js
src/redux/store/store.js

[ Grupo 19] - Start

---

src/components/GameQuestion.js
src/constants/index.js
src/redux/actions/index.js
src/redux/reducers/userReducer.js

[Grupo 22] Requisito 6 - Resposta Correta, Atualização do Reducer e Score Total

---

src/components/ButtonPlayGame.js
src/components/InputLogin.js
src/pages/Login.js
src/redux/reducers/reducerName.js
src/services/triviaAPI.js

---
[https://opentdb.com/api_token.php?command=request](https://opentdb.com/api_token.php?command=request)
[Open Trivia DB](https://opentdb.com/api_config.php)
---
- Artefato 1
- Artefato 2
Escreva abaixo suas observações, coloque o seu "*@user*" *na frente da observação*
---
@Thomas Ravache - Teste

[GRUPO 21] Criar Redirect e fazer Fetch da API do Trivia no onClick do botão jogar e Salvar no LocalStorage

---

src/components/GameAnswers.jsx
src/components/GameTimer.jsx
src/components/HeaderGame.jsx
src/components/NextBtn.jsx
src/helpers/shuffleAnswers.js
src/pages/Gamepage.jsx
src/redux/actions/game.js
src/redux/reducers/game.js
src/styles/Gamepage.css

[GRUPO 25] - Requisito 8

---

cypress/integration/project.spec.js
package-lock.json
package.json
src/components/Header.js
src/components/index.js
src/pages/GamePage.js
src/pages/Login.js
src/redux/reducer/user.js
src/services/Api.js

4. Crie um header que deve conter as informações da pessoa jogadora
PRIORIDADE 1 - O Header deve conter as informações sobre a pessoa jogadora, como a imagem do **Gravatar**, o nome e o placar
Observações técnicas:
O que será avaliado:
A imagem do Gravatar está presente no header
O nome da pessoa está presente no header
O placar zerado está presente no header

Main group 15 dev req4

---

src/components/Button.js
src/pages/Login.js
src/services/triviaAPI.js

[GRUPO 21] Criar o botão de configurações

---

src/pages/Feedbacks.js

---
```jsx
// Esta será a função que será enviada para os botões desta página
// Abaixo uma Sugestão de código
handleClick(testId) {
const { history } = this.props
if (testId === 'Ranking') {
history.push('/ranking');
} if (testId === 'Jogar Novamente!') {
history.push('/gamepage')
}
```
Vamos renderizar o código abaixo do Header da main, já renderizado no componente;
```jsx
const mapStateToProps = (state) => ({
score = state.results.score,
correctAnswers = state.result.correctAnswers,
});
```

[GRUPO 21] Criar conteúdo da página Feedback

---

src/App.js
src/components/NextBtn.jsx
src/pages/Feedback.jsx

[GRUPO 25] - Requisito 11

---

cypress/integration/project.spec.js
src/App.js
src/components/PlayAgain.jsx
src/components/ViewRanking.jsx
src/pages/Feedback.jsx
src/pages/Ranking.jsx

[GRUPO 25] - Requisito 16

---

cypress/integration/project.spec.js
src/App.js
src/components/GoHome.jsx
src/components/PlayAgain.jsx
src/components/ViewRanking.jsx
src/pages/Feedback.jsx
src/pages/Ranking.jsx

[GRUPO 25] - Requisito 18

---

cypress/integration/project.spec.js
src/App.js
src/actions/index.js
src/components/Buttons.js
src/components/Header.js
src/pages/Game.js
src/pages/feedBack.js
src/pages/ranking.js
src/reducers/index.js
src/reducers/sendFeedbakc.js

[Requisito 16]

---

package-lock.json
package.json
public/index.html
src/App.css
src/App.js
src/components/QuestionCard.jsx

Aguardar realização do teste pelo avaliador. `Npm run cy` não está funcionando localmente.

[Grupo 1] Requisito 07.

---

package-lock.json
src/components/Question.js
src/components/Timer.js
src/pages/Game.js

{Main group 20} requisito 8

---

src/redux/actions/index.js
src/redux/reducers/gameSettings.js
src/redux/reducers/index.js

[Grupo-21] develop-group-21-store-configs

---

src/component/GamePage.jsx

reparado erro de identação utilizando () após o ternário.

reparado erro lint, atende requisitos 5 e 6

---

src/App.js
src/components/JogoHeader.js
src/pages/Feedback.js
src/pages/Jogo.js
src/pages/Ranking.js

[ Grupo 16 ] dia 4

---

src/components/GameTimer.jsx
src/components/GoHome.jsx
src/components/NextBtn.jsx
src/components/PlayAgain.jsx
src/pages/Gamepage.jsx
src/redux/actions/game.js
src/redux/actions/timer.js
src/redux/reducers/game.js
src/redux/reducers/header.js
src/redux/reducers/index.js
src/redux/reducers/timer.js

[GRUPO 25] - Resolve Bug Jogar Novamente

---

src/pages/GamePage.js

```jsx
mapStateToProps = ({gameSettings: { difficulty, type, cattegory }}) => ({
configs: {
difficulty,
type,
category,
},
});
```

[Grupo-21] develop-group-21-map-state-to-props-game-page

---

src/components/Question.js
src/pages/GamePage.js

```jsx
componentDidMount() {
const { configs } = this.props;
const questions = mountQuestions(configs)
this.getQuestions(questions);
}
getQuestions(questions) {
this.setState({
questions,
loading: false,
})
}
```jsx
this.setState((prevState) => ({
questionIndex: prevState.questionIndex + 1
}));
```
```jsx
{ loading ? <p>Loading...</p> : <Question question={question[questionIndex]} /> } 
```

[ Group 21 ] Develop group 21 Questions Gamepage

---

cypress/integration/project.spec.js
src/components/GameTrivia.js
src/components/Header.js
src/pages/Login.js
src/redux/actions/actionType.js
src/redux/actions/index.js
src/redux/reducer/game.js
src/redux/reducer/user.js
src/services/localStoreService.js

-  [x] Você deve salvar a pontuação atual no `localStorage`.
-  [x] Soma pontos ao acertar uma questão.
-  [x] Respostas erradas não devem somar ao placar.

Main group 15 dev req09

---

src/services/fetchGame.js

---
Pela documentação da API, caso o token tenha expirado ou não exista, ao fazer uma busca com este token usando o seguinte endpoint : 
```jsx
https://opentdb.com/api.php?amount=10&token=YOURTOKENHERE
```
Você encontrará o seguinte resultado: `{"response_code":3,"results":[]}`
```jsx
const { category, difficulty, type } = actualConfig
```
``https://opentdb.com/api.php?encode=base64&amount=5&token=${token}&category=${category}&difficulty=${difficulty}&type=${type}&encode=base64``
Tente reduzir este endpoint de alguma forma, pode ser com alguma forma de concatenação, ou usando const para algum trecho que se repita, esta última é o mais comum no mercado, consulte a documentação, se preciso for:
[Open Trivia …

[GRUPO 21] Implementar função que realiza a busca das perguntas na API

---

src/App.css
src/components/Questions.js

14 requisito 7

---

src/App.css

corrige stylelint

---

src/App.js
src/components/FeedbackScore.js
src/components/Ranking.js
src/pages/Feedback.js

[Grupo 18] PR BOMBA! :bomb: Requisitos 14, 15 e 16

---

src/App.css
src/pages/GamePage.jsx
src/pages/Login.jsx
src/redux/action/index.js
src/redux/reducer/index.js
src/redux/reducer/questionReducer.js

[ Grupo 19] 

---

src/App.css
src/pages/GamePage.jsx

[Grupo 19] requisito 07

---

src/pages/GamePage.jsx

[Grupo 19] requisito 10

---

src/components/Select.js
src/pages/Configurations.js
src/services/fetchCategories.js

---
[Open Trivia DB](https://opentdb.com/api_config.php)
```jsx
return = response.trivia_categories
```
```jsx
[{"id":9,"name":"General Knowledge"},{"id":10,"name":"Entertainment: Books"},'etc']
```
```jsx
componentDidMount() {
// const state = JSON.parse(localStorage.getItem('state'));
//if (state.settings !== null) {
//this.mountSettings(state.settings);
//}
const { storedSetting } = this.props
this.mountSettings( storedSetting };
}
mountSettings(storedSetting) {
const { difficulty, type, category } = storedSetting;
this.setState({
difficulty,
type,
category,
});
}
```
```jsx
const mapStateToProps = (state) => ({ 
storedSetting: state.gameSettings 
});
```
Este é um componente que basicamente é um formulário de configuração do jogo, sendo …

[GRUPO 21] Criação da página de Configurações

---

src/components/Alternative.js
src/components/Question.js
src/pages/Game.js
src/reducers/game.js
src/reducers/index.js

Pessoal,
Esse PR confirma que os testes passam até o requisito 10.
Abraço

[Grupo 20] Corrige requisito 7 e confirma testes dos requisitos 8, 9 e 10

---

src/component/GamePage.jsx

faz um 'merge' manual dos requisitos 07, 09, 11

 faz um 'merge' manual dos requisitos 09, 07, 11

---

src/components/Alternative.js
src/components/Question.js
src/fetchers/index.js
src/pages/Game.js
src/reducers/game.js
src/reducers/index.js

Previne possíveis bugs nos próximos requisitos.

[Grupo 20] Melhora a lógica da obtenção do token

---

src/helpers/decodeHtml.js
src/helpers/shuffleAnswers.js
src/pages/Gamepage.jsx

Traduz a informação vinda da API com HTML encoding para uma string normal.

[GRUPO 25] - Traduz HTML encoding

---

cypress/integration/project.spec.js
src/App.js
src/pages/FeedBack.js
src/pages/Ranking.js

 atende requisito 16

---

public/index.html
src/App.css
src/components/Button.js
src/components/Header.js
src/components/HeaderConfig.js
src/components/InputLogin.js
src/components/Question.js
src/components/components-css/Header.css
src/components/components-css/HeaderConfig.css
src/components/components-css/Question.css
src/pages/Configurations.js
src/pages/Feedbacks.js
src/pages/GamePage.js
src/pages/Login.js
src/pages/Ranking.js
src/pages/pages-css/Configurations.css
src/pages/pages-css/Feedbacks.css
src/pages/pages-css/GamePage.css
src/pages/pages-css/Login.css
src/pages/pages-css/Ranking.css
src/redux/reducers/questions.js

---
[7. Desenvolva o estilo que, ao clicar em uma resposta, a correta deve ficar verde e as incorretas, vermelhas](https://www.notion.so/7-Desenvolva-o-estilo-que-ao-clicar-em-uma-resposta-a-correta-deve-ficar-verde-e-as-incorretas-v-face42411bbc4f2eb3c43b70439919b8)
Dica! Somos 5, e são 11 arquivos, se cada um ficar com 2 arquivos, e deixarmos a `Questions.css` para resolvermos em conjunto, poderemos alcançar um bom desempenho!
@Matheus Duarte de Freitas 
Escreva abaixo suas observações, coloque o seu "*@user*" *na frente da observação*
---

Develop group 21 css beautiful people

---

src/App.css
src/components/FeedbackMSG.jsx
src/components/Timer.js
src/pages/Play.js
src/reducers/play.js

-Correcao do bug do timer nao fazer contagem negativa
-Salvo tempo restante do relogio no estado timeLeft
-Criado estado para guardar as respostas e tirada a logica de .sort(0 do handle answers
-Correcao do bug das respostas embaralharem mais de uma vez

Correção de bug a partir da branch do requisito 9

---

src/App.css
src/actions/index.js
src/components/Timer.js
src/pages/Feedback.js
src/pages/Play.js
src/pages/Ranking.js
src/reducers/index.js
src/reducers/rank.js
src/reducers/user.js
src/services/index.js

Mudado o retorno da api para encode64 e usada a funcao window.atob(string) para decodificar as palavras que serão utilizadas vindo da API

 Requisito 17:

---

src/components/HeaderFeedback.jsx
src/pages/Jogo.jsx
src/pages/JogoConstante.js
src/pages/Ranking.css
src/pages/Ranking.jsx

Main group 3 desenvolvimento
